# Generated by Django 6.0 on 2025-12-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('expdate', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('date', models.DateField()),
            ],
        ),
    ]
